### ISSUE TITLE
will you relwase training code?

### ISSUE THREAD

**Issue by stanny880913** [HVXLab/HVDetFusion#2]
Hi~ Im very interesting in your paper, and I want t ask will you release training code for us to train it? I want to try to train my own dataset too!!!
Thank you for your help~

**Comment by Song-Jingyu** [comment]
Same question here! Thanks for open sourcing this work.

**Comment by ifve** [comment]
Thanks for your comment. According to the current policy requirements, it is very frustrating that the release of training code is not supported, and the content of the release may be adjusted in the future according to the follow-up relevant policies, looking forward to your continued attention.
